---
- name: Copy mongodb-org-3.2.repo
  copy:
    src: ../conf/mongodb-org-3.2.repo
    dest: /etc/yum.repos.d/mongodb-org-3.2.repo
    owner: root
    group: root
  become: yes
- name: Yum update
  yum:
    name: "*"
    state: latest
  become: yes
- name: Install MongoDB
  yum:
    name: mongodb-org
    enablerepo: "mongodb-org-3.2"
  become: yes
- name: Start MongoDB
  service:
    name: mongod
    state: started
  become: yes
  changed_when: False
# https://docs.mongodb.org/v3.0/tutorial/transparent-huge-pages/
- name: Copy init.d script
  copy:
    src: ../conf/disable-transparent-hugepages
    dest: /etc/init.d/disable-transparent-hugepages
    force: no
  become: yes
- name: Make it executable
  file:
    path: /etc/init.d/disable-transparent-hugepages
    owner: root
    group: root
    mode: 755
  become: yes
- name: Configure to run it on boot
  shell: chkconfig --add disable-transparent-hugepages
  become: yes
  changed_when: False
- name: Create a directory /etc/tuned/no-thp
  file:
    path: /etc/tuned/no-thp
    state: directory
    owner: root
  become: yes
- name: Copy init.d script
  copy:
    src: ../conf/tuned.conf
    dest: /etc/tuned/no-thp/tuned.conf
    force: no
  become: yes
- name: Enable the new profile
  shell: tuned-adm profile no-thp
  become: yes
  changed_when: False
- name: Edit limits.conf (hard nproc 32000)
  lineinfile:
    line: "mongod hard nproc 32000"
    insertbefore: "# End of file"
    dest: /etc/security/limits.conf
  become: yes
- name: Edit limits.conf (soft nproc 32000)
  lineinfile:
    line: "mongod soft nproc 32000"
    insertbefore: "# End of file"
    dest: /etc/security/limits.conf
  become: yes
- name: Edit limits.conf (hard nofile 64000)
  lineinfile:
    line: "mongod hard nofile 64000"
    insertbefore: "# End of file"
    dest: /etc/security/limits.conf
  become: yes
- name: Edit limits.conf (hard nofile 64000)
  lineinfile:
    line: "mongod hard nofile 64000"
    insertbefore: "# End of file"
    dest: /etc/security/limits.conf
  become: yes
- name: Reboot
  command: shutdown -r 1
  async: 0
  poll: 0
  become: yes
  changed_when: False
- name: Wait for connection to be down
  wait_for:
    host: "{{ ansible_ssh_host }}"
    state: stopped
    delay: 60
    timeout: 20
  connection: local
  become: no
  ignore_errors: True
- name: Wait for connection to be up
  wait_for:
    host: "{{ ansible_ssh_host }}"
    delay: 30
    timeout: 60
    state: started
  connection: local
  become: no
  ignore_errors: True
...
