---
- name: Upgrade packages (Ubuntu)
  apt:
    update_cache: yes
    upgrade: full
  become: yes
  when: ansible_os_family == "Debian"
- name: Update packages (RedHat)
  yum:
    name: "*"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- name: Reboot
  command: shutdown -r 1
  async: 0
  poll: 0
  become: yes
  changed_when: False
- name: Wait for connection to be down
  wait_for:
    host: "{{ ansible_ssh_host }}"
    state: stopped
    delay: 60
    timeout: 20
  connection: local
  become: no
  ignore_errors: True
- name: Wait for connection to be up
  wait_for:
    host: "{{ ansible_ssh_host }}"
    delay: 30
    timeout: 60
    state: started
  connection: local
  become: no
  ignore_errors: True
...
