---
- name: check if MeCab exists
  shell: "mecab --version"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: mecab
  ignore_errors: True
  changed_when: False
- name: install gcc-c++ (Ubuntu)
  apt:
    pkg: "build-essential"
  become: yes
  when: mecab|failed and ansible_os_family == "Debian"
- name: install gcc-c++ (RedHat)
  yum:
    name: "gcc-c++"
    state: latest
  become: yes
  when: mecab|failed and ansible_os_family == "RedHat"
- name: download MeCab
  get_url:
    url: "{{ mecab_url }}"
    dest: /tmp/mecab-0.996.tar.gz
  become: yes
  when: mecab|failed
- name: unpack MeCab
  unarchive:
    src: /tmp/mecab-0.996.tar.gz
    dest: /tmp
    copy: no
  become: yes
  when: mecab|failed
- name: install MeCab
  shell: |
    ./configure
    make check
    make
    make install
  args:
    chdir: "/tmp/mecab-0.996"
  become: yes
  when: mecab|failed
- name: update libraries
  command: /sbin/ldconfig
  become: yes
  when: mecab|failed
...
