# vim:ft=ansible:
# for Red Hat Enterprise Linux 7
- hosts: nlp100
  sudo: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Install essential tools
      yum:
        name: "{{ item }}"
      with_items:
        - wget
        - git
        - gcc-c++
    - name: Install EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
    - name: Copy mongodb-org-3.0.repo
      synchronize:
        src: mongodb-org-3.0.repo
        dest: /etc/yum.repos.d/mongodb-org-3.0.repo
    - name: Copy bintray-sbt-rpm.repo
      synchronize:
        src: bintray-sbt-rpm.repo
        dest: /etc/yum.repos.d/bintray-sbt-rpm.repo
    - name: Yum Update
      yum:
        name: *
        state: latest
    - name: Install sbt
      yum:
        name: sbt
        state: latest
        enablerepo: bintray--sbt-rpm
    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: latest
        enablerepo: "mongodb-org-3.0"
    - name: Install Redis
      yum:
        name: redis
        state: latest
    - name: Check if MeCab exists
      shell: which mecab
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      ignore_errors: True
      register: mecab
      changed_when: False
    - name: Download MeCab
      get_url:
        url: "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE"
        dest: /tmp/mecab-0.996.tar.gz
      when: mecab|failed
    - name: Unpack MeCab
      command: tar -xzvf /tmp/mecab-0.996.tar.gz -C /tmp
      when: mecab|failed
    - name: Install MeCab
      shell: |
        ./configure
        make check
        make
        make install
      args:
        chdir: "/tmp/mecab-0.996"
      when: mecab|failed
